name: Cypress Tests

on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
      # ScreenShots
      - name: Create Screenshots folder
        run: |
          ls
      - name: Upload Screenshots
        uses: actions/upload-artifact@v1
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Videos
      - name: Create Videos folder
        run: |
          sudo mkdir cypress/videos
      - name: Videos
        uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: cypress-videos
          path: cypress/videos