name: Deploy on release

# Run this workflow every time a new commit pushed to your repository
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: npm install
      - name: Build App
        run: npm run build
      - name: install firebase
        run: npm i firebase-tools -g
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}